import type { Issue } from './types';

export const initialIssues: Issue[] = [
  {
    id: 'IS-101',
    issue_type: 'Traffic',
    location: 'Main St & 1st Ave',
    description: 'Traffic light is malfunctioning, causing major delays and a potential safety risk. It has been this way for 3 days.',
    name: 'Alice Johnson',
    creator_email: 'alice.j@example.com',
    timestamp: '2024-07-15T09:00:00Z',
    status: 'Pending',
  },
  {
    id: 'IS-102',
    issue_type: 'Civic',
    location: 'City Park',
    description: 'Large pothole in the main pathway. Several people have tripped. This is an urgent safety hazard.',
    name: 'Bob Williams',
    creator_email: 'bob.w@example.com',
    timestamp: '2024-07-14T14:30:00Z',
    status: 'In Progress',
  },
  {
    id: 'IS-103',
    issue_type: 'Crime',
    location: 'Downtown Alley',
    description: 'Graffiti and vandalism on several buildings. Reported last week, no action taken yet.',
    name: 'Charlie Brown',
    creator_email: 'charlie.b@example.com',
    timestamp: '2024-07-12T11:20:00Z',
    status: 'Pending',
  },
  {
    id: 'IS-104',
    issue_type: 'Event',
    location: 'Community Center',
    description: 'Request for additional security for the upcoming summer festival due to a security breach last year.',
    name: 'Diana Prince',
    creator_email: 'diana.p@example.com',
    timestamp: '2024-07-18T18:00:00Z',
    status: 'Completed',
  },
  {
    id: 'IS-105',
    issue_type: 'Other',
    location: 'Oak Street',
    description: 'Streetlights are out on the entire block. This is a recurring issue and needs a permanent fix.',
    name: 'Ethan Hunt',
    creator_email: 'ethan.h@example.com',
    timestamp: '2024-07-17T22:00:00Z',
    status: 'In Progress',
  },
  {
    id: 'IS-106',
    issue_type: 'Civic',
    location: 'Riverside Library',
    description: 'Broken water fountain, has been leaking for a week. Water damage is becoming a concern.',
    name: 'Fiona Glenanne',
    creator_email: 'fiona.g@example.com',
    timestamp: '2024-07-16T13:45:00Z',
    status: 'On Hold',
  },
  {
    id: 'IS-107',
    issue_type: 'Traffic',
    location: 'Highway 5 Exit Ramp',
    description: 'Faded lane markings are causing confusion and near-accidents, especially at night.',
    name: 'George Mason',
    creator_email: 'george.m@example.com',
    timestamp: '2024-07-13T08:15:00Z',
    status: 'Completed',
  },
  {
    id: 'IS-108',
    issue_type: 'Crime',
    location: 'Westside Mall Parking',
    description: 'Reports of several car break-ins over the past weekend. Urgent need for increased patrols.',
    name: 'Hannah Abbott',
    creator_email: 'hannah.a@example.com',
    timestamp: '2024-07-19T10:00:00Z',
    status: 'Pending',
  },
];
